### ISSUE TITLE
loss计算那里 RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by hhy150** [codefuse-ai/MFTCoder#22]
train_utils.py文件中 175行开始，报错：RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn。大家有这个问题吗？
~~~python
                    # backward
                    if not torch.isnan(loss):
                        total_loss += loss.detach().float()  
                    accelerator.backward(loss)  # RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

~~~
Traceback (most recent call last):
  File "mft_accelerate.py", line 375, in <module>
    main()
  File "mft_accelerate.py", line 371, in main
    accelerate_train(accelerator, model, train_dataloader, valid_dataloader, optimizer, lr_scheduler, num_update_steps_per_epoch, len(train_dataset), args)
  File "/data2/hhy/QwenCode/pefts/train_utils.py", line 178, in accelerate_train
    accelerator.backward(loss)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1862, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1901, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/data2/hhy/anaconda3/envs/CodeFT/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by amulil** [comment]
参考：https://github.com/huggingface/peft/issues/137

`model = get_peft_model(model, peft_config)` 前加 `model.enable_input_require_grads()` 报错消失

**Comment by twelveand0** [comment]
Thanks for your issue and solution.

**Comment by fclearner** [comment]
Hi, can you explain what the root cause of this issue is? I've tried using model.enable_input_require_grads() before get_peft_model(), its not working！I've frozen all other modules and am only training the PEFT module.
