### ISSUE TITLE
Something wrong when run 'bash run_bash.sh'

### ISSUE THREAD

**Issue by MaoYouSi** [codefuse-ai/MFTCoder#27]
# Error
当我尝试跑 ```bash run_bash.sh```时候遇到了如下错误。
```
trainable params: 80,510,976 || all params: 1,917,339,648 || trainable%: 4.1990982705636934
QWenConfig {
  "_name_or_path": "/home/jovyan/mys/MFTCoder/Qwen-1_8B",
  "architectures": [
    "QWenLMHeadModel"
  ],
  "attn_dropout_prob": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_qwen.QWenConfig",
    "AutoModelForCausalLM": "modeling_qwen.QWenLMHeadModel"
  },
  "bf16": true,
  "emb_dropout_prob": 0.0,
  "fp16": false,
  "fp32": false,
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "kv_channels": 128,
  "layer_norm_epsilon": 1e-06,
  "max_position_embeddings": 8192,
  "model_type": "qwen",
  "no_bias": true,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "onnx_safe": null,
  "rotary_emb_base": 10000,
  "rotary_pct": 1.0,
  "scale_attn_weights": true,
  "seq_length": 8192,
  "tie_word_embeddings": false,
  "tokenizer_class": "QWenTokenizer",
  "transformers_version": "4.32.0",
  "use_cache": false,
  "use_dynamic_ntk": true,
  "use_flash_attn": true,
  "use_logn_attn": false,
  "vocab_size": 151936
}

Using /home/jovyan/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/jovyan/.cache/torch_extensions/py310_cu117/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /opt/conda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/envs/MFTCoder/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -std=c++17 -c /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/opt/conda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/envs/MFTCoder/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -std=c++17 -c /opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
cc1plus: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/envs/MFTCoder/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jovyan/mys/MFTCoder/mft_peft_hf/src/pefts/mft_accelerate.py", line 391, in <module>
    main()
  File "/home/jovyan/mys/MFTCoder/mft_peft_hf/src/pefts/mft_accelerate.py", line 345, in main
    optimizer = adam_optimizer(
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
    return self.jit_load(verbose)
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
    op_module = load(name=self.name,
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24533) of binary: /opt/conda/envs/MFTCoder/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/MFTCoder/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/accelerate/commands/launch.py", line 964, in launch_command
    deepspeed_launcher(args)
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/accelerate/commands/launch.py", line 687, in deepspeed_launcher
    distrib_run.run(args)
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/MFTCoder/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
mft_accelerate.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-18_11:35:10
  host      : 5218d9e68659
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24533)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
# 一些补充

```nvcc --version```信息如下
```dotnetcli
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
```
关于ninja
```dotnetcli

ninja --version
1.11.1.git.kitware.jobserver-1
```

```dotnetcli
echo $?
0
```
各类包的信息
```dotnetcli
Package                       Version
----------------------------- ------------
absl-py                       2.0.0
accelerate                    0.21.0
aiohttp                       3.9.1
aiosignal                     1.3.1
async-timeout                 4.0.3
attrs                         23.1.0
bitsandbytes                  0.40.2
cachetools                    5.3.2
certifi                       2023.11.17
charset-normalizer            3.3.2
cmake                         3.28.1
datasets                      2.15.0
deepspeed                     0.9.3
dill                          0.3.7
einops                        0.7.0
evaluate                      0.4.1
filelock                      3.13.1
flash-attn                    2.3.6
frozenlist                    1.4.1
fsspec                        2023.10.0
ftfy                          6.1.3
google-auth                   2.25.2
google-auth-oauthlib          1.2.0
grpcio                        1.60.0
hjson                         3.1.0
huggingface-hub               0.19.4
idna                          3.6
Jinja2                        3.1.2
jsonlines                     4.0.0
lit                           17.0.6
Markdown                      3.5.1
MarkupSafe                    2.1.3
mpmath                        1.3.0
multidict                     6.0.4
multiprocess                  0.70.15
networkx                      3.2.1
ninja                         1.11.1.1
numpy                         1.26.2
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu11             10.9.0.58
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu11            10.2.10.91
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu11          11.7.4.91
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu11              2.14.3
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu11              11.7.91
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.2.2
packaging                     23.2
pandas                        2.1.4
peft                          0.4.0
Pillow                        10.1.0
pip                           23.3.1
protobuf                      4.23.4
psutil                        5.9.7
py-cpuinfo                    9.0.0
pyarrow                       14.0.1
pyarrow-hotfix                0.6
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pybind11                      2.11.1
pydantic                      1.10.13
python-dateutil               2.8.2
pytz                          2023.3.post1
PyYAML                        6.0.1
regex                         2023.10.3
requests                      2.31.0
requests-oauthlib             1.3.1
responses                     0.18.0
rsa                           4.9
safetensors                   0.4.1
scipy                         1.11.4
sentencepiece                 0.1.99
setuptools                    68.2.2
six                           1.16.0
sympy                         1.12
tensorboard                   2.15.1
tensorboard-data-server       0.7.2
tiktoken                      0.5.2
tokenizers                    0.13.3
torch                         2.0.1
torchaudio                    2.1.2
torchvision                   0.16.2
tqdm                          4.66.1
transformers                  4.32.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.9.0
tzdata                        2023.3
ujson                         5.9.0
urllib3                       2.1.0
wcwidth                       0.2.12
Werkzeug                      3.0.1
wheel                         0.41.2
xformers                      0.0.21
xxhash                        3.4.1
yarl                          1.9.4
zstandard                     0.22.0
```

**Comment by twelveand0** [comment]
你好，
```
cc1plus: fatal error: cuda_runtime.h: No such file or directory
```
错误的根因是**未能找到cuda_runtime.h**头文件，这通常是由于cuda安装不正确或没有把cuda安装路径配置到PATH等环境变量中导致的，你可以如下设置环境变量
```
export CUDA_HOME=<替换成你的cuda安装目录路径>
export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"
export PATH="${CUDA_HOME}/bin:${PATH}"
````
