### ISSUE TITLE
mftcoder 新版 Permission denied: '/home/admin' BUG

### ISSUE THREAD

**Issue by Chaochao2020** [codefuse-ai/MFTCoder#60]
你好，之前就一直在使用该框架，最近几天在微信公众号上看到了发布了新版 mftcoder 支持了更多模型，所以 git pull 下来尝试运行，但在使用相同的虚拟环境下新版 mftcoder 会有如下报错：

```bash
Traceback (most recent call last):
  File "/home/chao.cui/Github-NIO/MFTCoder/mftcoder_accelerate/src/pefts/mft_accelerate.py", line 611, in <module>
    main()
  File "/home/chao.cui/Github-NIO/MFTCoder/mftcoder_accelerate/src/pefts/mft_accelerate.py", line 594, in main
    trainer = MftTrainer(
  File "/home/chao.cui/Github-NIO/MFTCoder/mftcoder_accelerate/src/pefts/trainer.py", line 153, in __init__
    self.default_writer = SummaryWriter(log_dir="/home/admin/logs/tfevent")
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 247, in __init__
    self._get_file_writer()
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 900, in makedirs
    return get_filesystem(path).makedirs(path)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 201, in makedirs
    os.makedirs(path, exist_ok=True)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/admin'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15951) of binary: /home/chao.cui/.conda/envs/mtfcoder_new/bin/python
Traceback (most recent call last):
  File "/home/chao.cui/.conda/envs/mtfcoder_new/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1042, in launch_command
    deepspeed_launcher(args)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/accelerate/commands/launch.py", line 754, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/chao.cui/.conda/envs/mtfcoder_new/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pefts/mft_accelerate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 15952)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 15953)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 15954)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 15955)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 15956)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 15957)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 15958)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-08_03:08:44
  host      : rejected-fixed-andale-dnz-chao-cui-master-0.rejected-fixed-andale-dnz-chao-cui.wsgo-chao-cui.svc.cluster.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15951)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Chaochao2020** [comment]
最开始我以为是新版对一些包的版本有了新的要求，所以我尝试重新创建了虚拟环境来重新跑但还是有这个报错，我还尝试在老版本上跑却能够跑通。下面是我的一些环境配置：
```bash
Package                       Version
----------------------------- ------------
absl-py                       2.1.0
accelerate                    0.28.0
aiohttp                       3.9.4
aiosignal                     1.3.1
annotated-types               0.6.0
async-timeout                 4.0.3
attrs                         23.2.0
bitsandbytes                  0.43.0
cachetools                    5.3.3
certifi                       2024.2.2
charset-normalizer            3.3.2
cmake                         3.29.1
datasets                      2.18.0
deepspeed                     0.14.0
dill                          0.3.8
einops                        0.7.0
filelock                      3.13.4
flash-attn                    2.5.9.post1
frozenlist                    1.4.1
fsspec                        2024.2.0
ftfy                          6.2.0
google-auth                   2.29.0
google-auth-oauthlib          0.4.6
grpcio                        1.62.1
hjson                         3.1.0
huggingface-hub               0.22.2
idna                          3.7
Jinja2                        3.1.3
joblib                        1.3.2
jsonlines                     4.0.0
lit                           18.1.2
Markdown                      3.6
MarkupSafe                    2.1.5
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
networkx                      3.3
ninja                         1.11.1.1
numpy                         1.23.5
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu11             10.9.0.58
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu11            10.2.10.91
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu11          11.7.4.91
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu11              2.14.3
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.5.40
nvidia-nvtx-cu11              11.7.91
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.2.2
packaging                     24.0
pandas                        1.5.3
peft                          0.10.0
pillow                        10.2.0
pip                           23.3.1
protobuf                      3.20.3
psutil                        5.9.8
py-cpuinfo                    9.0.0
pyarrow                       15.0.2
pyarrow-hotfix                0.6
pyasn1                        0.6.0
pyasn1_modules                0.4.0
pybind11                      2.12.0
pydantic                      1.10.15
pynvml                        11.5.0
python-dateutil               2.9.0.post0
pytz                          2024.1
PyYAML                        6.0.1
regex                         2023.12.25
requests                      2.31.0
requests-oauthlib             2.0.0
rsa                           4.9
safetensors                   0.4.2
scipy                         1.12.0
sentencepiece                 0.2.0
setuptools                    68.2.2
six                           1.16.0
sympy                         1.12
tensorboard                   2.11.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
threadpoolctl                 3.3.0
tiktoken                      0.6.0
tokenizers                    0.19.1
torch                         2.0.1+cu117
torchvision                   0.15.2+cu117
tqdm                          4.66.2
transformers                  4.40.2
transformers-stream-generator 0.0.5
triton                        2.0.0
typing_extensions             4.11.0
ujson                         5.9.0
urllib3                       2.2.1
wcwidth                       0.2.13
Werkzeug                      3.0.2
wheel                         0.41.2
xformers                      0.0.22.post7
xxhash                        3.4.1
yarl                          1.9.4


```bash
{
    "data_paths": "[data/ai2_arc,data/squad,data/commonsense_qa]",
    "output_dir": "model/mistral/single_train_2024-06-06/lora_adaptor",
    "tb_dir": "model/mistral/single_train_2024-06-06/tensorboard",
    "pretrained_model_path": "/home/chao.cui/.cache/modelscope/hub/AI-ModelScope/Mistral-7B-Instruct-v0___2",
    "model_type": "mistral",
    "load_raw_dataset": true,
    "data_split": "99,1,0",
    "padding_mode": "padding",
    "use_dynamic_padding": true,
    "tokenize_mode": "sft",
    "tokenizer_type": "AutoTokenizer",
    "weighted_loss_mode": "case3",
    "attn_implementation": "flash_attention_2",
    "seq_length": 512,
    "seed": 1234,
    "peft_type": "lora",
    "quantization": null,
    "lora_rank": 96,
    "lora_alpha": 32,
    "lora_dropout": 0.05,
    "per_device_train_batch_size": 16,
    "per_device_eval_batch_size": 32,
    "learning_rate": 5e-5,
    "min_lr": 5e-6,
    "weight_decay": 0.1,
    "gradient_accumulation_steps": 2,
    "lr_scheduler_type": "cosine",
    "num_warmup_steps": 300,
    "num_train_epochs": 3,
    "resume_from_checkpoint": null,
    "log_interval": 10,
    "checkpointing_steps": 100,
    "evaluation_steps": 100,
    "max_train_steps": null,
    "epoch_checkpointing": true,
    "shuffle_before_split": true,
    "early_stopping": true,
    "early_stopping_stall_num": 5,
    "saving_limit": null,
    "target_modules":["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "down_proj", "up_proj"]

}

**Comment by Chaochao2020** [comment]
顺便祝一下你们端午节快乐哟😁

**Comment by Chaochao2020** [comment]
我查阅了原因，估计是因为我的 CUDA 版本太低了，才 11.7。安装 torch 2.1 时适配的 CUDA 为 12.1，总之就是版本不兼容，但奇怪的是我之前用的时候是可以用的没注意到这么点。

**Comment by chencyudel** [comment]
@Chaochao2020 关于第一个报错，我们这里修复了关于那个permission的问题，原因是我们引入了一个默认的tensorboard写入地址，这个地址有可能在你的环境中是没有权限的，所以我们将这个默认地址删除了，只保留用户自定义的tb_dir作为tensorboard写入地址。您可以尝试v0.4.3.

**Comment by Chaochao2020** [comment]
你好，问题已经解决了，谢谢。
