### ISSUE TITLE
使用lora + zero3微调CodeFuse-CodeLlama-34B后，合并模型失败

### ISSUE THREAD

**Issue by 3m123** [codefuse-ai/MFTCoder#8]
使用lora + zero3微调CodeFuse-CodeLlama-34B后，合并模型失败。
配置文件：
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
mixed_precision: 'bf16'
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: false

合并时报错如下：
Traceback (most recent call last):
  File "merge_base_and_lora_to_hf.py", line 50, in <module>
    model_to_merge = PeftModel.from_pretrained(base_model, lora_adapter)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/peft/peft_model.py", line 271, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/peft/peft_model.py", line 556, in load_adapter
    adapters_weights = torch.load(
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/0: invalid header or archive is corrupted

**Comment by 3m123** [comment]
改为zero3后因提示tensor不在同一设备，所以对model/llama2/modeling_llama.py内的apply_rotary_pos_emb方法做了如下修改

def apply_rotary_pos_emb(q, k, cos, sin, position_ids):
    # The first two dimensions of cos and sin are always 1, so we can `squeeze` them.
    cos = cos.squeeze(1).squeeze(0)  # [seq_len, dim]
    sin = sin.squeeze(1).squeeze(0)  # [seq_len, dim]
    修改内容 cos = cos.to(position_ids.device)
    cos = cos[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
    修改内容 sin = sin.to(position_ids.device)
    sin = sin[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed

**Comment by 3m123** [comment]
adapter_model.bin 已生成

**Comment by wj882018** [comment]
为其他开发者提供了案例，感谢您的支持
